name: Node.js CI/CD with ArgoCD

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: "arunk369/nodejs-app"
  NEXUS_REPO: "http://3.144.225.80:5000"
  TRIVY_IMAGE: "aquasec/trivy"
  SONAR_HOST_URL: "http://3.144.225.80:9000"
  SONAR_PROJECT_KEY: "My-App"

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Docker Image
        run: |
          docker build --no-cache -t $DOCKER_IMAGE:${{ github.sha }} .
          docker tag $DOCKER_IMAGE:${{ github.sha }} $DOCKER_IMAGE:latest

      - name: Trivy Vulnerability Scan
        run: |
          docker pull $TRIVY_IMAGE
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock $TRIVY_IMAGE image $DOCKER_IMAGE:${{ github.sha }}

      - name: OWASP ZAP API Security Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:3000"
          fail_action: true

      - name: Push Docker Image to Nexus
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          echo "$NEXUS_PASS" | docker login $NEXUS_REPO -u "$NEXUS_USER" --password-stdin
          docker tag $DOCKER_IMAGE:${{ github.sha }} $NEXUS_REPO/$DOCKER_IMAGE:${{ github.sha }}
          docker tag $DOCKER_IMAGE:${{ github.sha }} $NEXUS_REPO/$DOCKER_IMAGE:latest
          docker push $NEXUS_REPO/$DOCKER_IMAGE:${{ github.sha }}
          docker push $NEXUS_REPO/$DOCKER_IMAGE:latest
